trigger:
  branches:
    include:
    - main
  paths:
    include:
    - deploy/database/*

variables:
  - group: Database-Credentials

stages:
- stage: DeployDatabase
  jobs:
  - deployment: Deploy
    environment: staging
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          
          - task: PowerShell@2
            inputs:
              targetType: 'filePath'
              filePath: '$(System.DefaultWorkingDirectory)/deploy/database/deploy.ps1'
              arguments: >
                -ServerName "$(SqlServerName)"
                -DatabaseName "$(DatabaseName)"
                -Username "$(SqlUsername)"
                -Password "$(SqlPassword)"